name: Deploy (Dev)
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.17.0'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: cd functions && npm i
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: secret-toymaker-dev
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project has been deployed to dev."
